### ISSUE TITLE
I'm getting ProxyError at live server!

### ISSUE THREAD

**Issue by kachkolasa** [MultiSafepay/multisafepay-python-wrapper#5]
Hello there, 
On my client request, I had to work with MSF and it was going great at the localhost but suddenly when I host it up on pythonanywhere I got a ProxyError. 
HTTPSConnectionPool(host='testapi.multisafepay.com', port=443): Max retries exceeded with url: /v1/json/orders (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))

What can be the reason?
![image](https://user-images.githubusercontent.com/72012513/153410340-49495d1b-e84f-412d-880e-0fe348c115d5.png)

**Comment by kachkolasa** [comment]
### Just writing this so that if someone is facing the same issue.
This was not the Multisafepay but the free hosting I was using, pythonanywhere.

**Comment by danielcivit** [comment]
Thanks for your comment @kachkolasa.

I remember we deal with this issue weeks ago via our internal ticket system and the problem was related with pythonanywhere free account hosting.  

In case this information can be useful for somebody else, for free accounts in pythonanywhere,  need to request include our endpoint in a whitelist. You can check the whitelist list for free account users in the following link: https://www.pythonanywhere.com/whitelist/

Somehow this GitHub issue was out of my radar. Thanks for comming back and update it. Now I am going to close it.
